## レコメンデーション2

In [1]:
import numpy as np
import pandas as pd

In [2]:
data1 = pd.DataFrame({"ゼロから作るDeepLearning":[2,1,0,2,1],
                       "Python機械学習プログラミング":[2,1,5,4,3],
                       "ゼロから作るDeepLearning-自然言語処理編-":[4,2,2,2,0],
                       "はじめてのパターン認識":[np.nan,4,2,3,4],
                      "これからの強化学習":[np.nan, 3,5,4,1]},index=["user1","user2","user3","user4","user5"])

In [3]:
data1

,ゼロから作るDeepLearning,Python機械学習プログラミング,ゼロから作るDeepLearning-自然言語処理編-,はじめてのパターン認識,これからの強化学習
user1,2,2,4,NaN,NaN
user2,1,1,2,4.0,3.0
user3,0,5,2,2.0,5.0
user4,2,4,2,3.0,4.0
user5,1,3,0,4.0,1.0

In [6]:
#欠損値は0で埋める
data2 = data1.fillna(0)

In [5]:
data2

,ゼロから作るDeepLearning,Python機械学習プログラミング,ゼロから作るDeepLearning-自然言語処理編-,はじめてのパターン認識,これからの強化学習
user1,2,2,4,0.0,0.0
user2,1,1,2,4.0,3.0
user3,0,5,2,2.0,5.0
user4,2,4,2,3.0,4.0
user5,1,3,0,4.0,1.0

【問題2】非負値行列因子分解(NMF)をScikit-learnで実装

In [8]:
X = np.array(data2)
X

array([[2., 2., 4., 0., 0.],
       [1., 1., 2., 4., 3.],
       [0., 5., 2., 2., 5.],
       [2., 4., 2., 3., 4.],
       [1., 3., 0., 4., 1.]])

In [9]:
from sklearn.decomposition import NMF
item_num = len(X[0])
model = NMF(n_components=5, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_

In [16]:
# WとHの積を計算
M = np.dot(W,H)
M

array([[1.99928657e+00, 1.99967792e+00, 4.00072450e+00, 8.18770123e-04,
        2.21371702e-04],
       [1.00161595e+00, 1.00035948e+00, 1.99843483e+00, 4.00000515e+00,
        3.00004628e+00],
       [1.27746700e-04, 5.00013473e+00, 2.00004665e+00, 2.00002013e+00,
        5.00002249e+00],
       [1.99986434e+00, 4.00020005e+00, 2.00008420e+00, 2.99997673e+00,
        3.99997275e+00],
       [1.00009450e+00, 2.99990819e+00, 5.30655635e-03, 4.00001327e+00,
        1.00004167e+00]])

今回はKaggleのアニメのデータセットでレコメンドしてみます。

'anime.csv', 'rating.csv'のファイルをダウンロード

In [17]:
# データの読み込み
ratings = pd.read_csv('./ard/rating.csv')
anime = pd.read_csv('./ard/anime.csv')
# 1000人以上評価しているもののみを取得
anime = anime[anime['members'] > 1000]
# 未評価のものは-1が入っているが、nanのものは削除
anime = anime.dropna()
ratings[ratings.rating == -1]=0
# マージ
merge_df = ratings.merge(anime, left_on = 'anime_id', right_on = 'anime_id', suffixes= ['_user', '']) 
# 重複しているものを削除
merge_df = merge_df.drop_duplicates(['user_id','name'])
anime_pivot = merge_df.pivot(index= 'user_id',columns='name',values='rating').fillna(0)
anime_pivot.head()

name,&quot;0&quot;,&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi,&quot;Bungaku Shoujo&quot; Memoire,&quot;Bungaku Shoujo&quot; Movie,.hack//G.U. Returner,.hack//G.U. Trilogy,.hack//G.U. Trilogy: Parody Mode,.hack//Gift,.hack//Intermezzo,.hack//Liminality,...,gdgd Fairies,gdgd Fairies 2,iDOLM@STER Xenoglossia,iDOLM@STER Xenoglossia Specials,s.CRY.ed,xxxHOLiC,xxxHOLiC Kei,xxxHOLiC Movie: Manatsu no Yoru no Yume,xxxHOLiC Rou,xxxHOLiC Shunmuki
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,8.11,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0

In [18]:
X = np.array(anime_pivot)

In [22]:
item_num = len(X[0])
item_num

6634

In [ ]:
model = NMF(n_components=item_num, init='random', random_state=0)
W = model.fit_transform(X)
H = model.components_